version: "3.9"

services:
  db:
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3310:3306"
    networks:
      default:
        aliases:
          - db
  web:
    build: .
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data:
